services:
  farmer-service:
    build: ./farmer-service
    ports:
      - "4001:4001"
    env_file:
      - ./farmer-service/.env

  order-service:
    build: ./order-service
    ports:
      - "4002:4002"
    env_file:
      - ./order-service/.env

  payment-service:
    build: ./payment-service
    ports:
      - "4003:4003"
    env_file:
      - ./payment-service/.env
