apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmer-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: farmer

  template:
    metadata:
      labels:
        app: farmer

    spec:
      containers:
        - name: farmer-container
          image: farmer-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4001
