apiVersion: v1
kind: Service
metadata:
  name: farmer-service
  labels:
    app: farmer

spec:
  type: NodePort

  selector:
    app: farmer

  ports:
    - name: http
      port: 4001
      targetPort: 4001
      nodePort: 30007
